# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

env:
  SCREENER_API_KEY: ${{secrets.SCREENER_API_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEYS: ${{secrets.SAUCE_ACCESS_KEYS}}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies 📦
        run: |
        cd learn-testing-and-dev
        npm ci
      - name: Build the app 🏗️
        run: |
          cd learn-testing-and-dev
          npm run build --if-present
      - name: Run component tests 🧪
        run: |
          cd learn-testing-and-dev
          npm test
      - name: Start the app ✨
        run: |
          cd learn-testing-and-dev
          npm start &
          npx wait-on --timeout 60000
